import json

# Define your branch names and their IDs
branches = [
    (1,'HEAD OFFICE'),
    (2,'CORPORATE OFFICE'),
    (3,'NUGEGODA'),
    (4,'NEGOMBO'),
    (5,'KANDY'),
    (6,'BADULLA'),
    (7,'PANADURA'),
    (8,'ANURADHAPURA'),
    (9,'GALLE'),
    (10,'KIRIBATHGODA'),
    (11,'KURUNEGALA'),
    (12,'RATHNAPURA'),
    (13,'MATARA'),
    (14,'KALUTARA'),
    (15,'AMBALANGODA'),
    (16,'AMPARA'),
    (17,'AVISSAWELLA'),
    (18,'GAMPAHA'),
    (19,'CHILAW'),
    (20,'POLONNARUWA'),
    (21,'PILIYANDALA'),
    (22,'BORALESGAMUWA'),
    (23,'DAMBULLA'),
    (24,'BALANGODA'),
    (25,'KEGALLE'),
    (26,'BANDARAWELA'),
    (27,'DEHIWALA'),
    (28,'EMBILIPITIYA'),
    (29,'BATTICALOA'),
    (30,'ELPITIYA'),
    (31,'MARADANA'),
    (32,'KANDANA'),
    (33,'MAHIYANGANAYA'),
    (34,'TISSAMAHARAMA'),
    (35,'MATALE'),
    (36,'MAHARAGAMA'),
    (37,'KULIYAPITIYA'),
    (38,'PUTTALAM'),
    (39,'TRINCOMALEE'),
    (40,'GAMPOLA'),
    (41,'HORANA'),
    (42,'KADAWATHA'),
    (43,'JAFFNA'),
    (44,'CHUNNAKAM'),
    (45,'MANIPAY'),
    (46,'CHAVAKACHCHERI'),
    (47,'KILINOCHCHI'),
    (48,'VAVUNIYA'),
    (49,'NUWARAELIYA'),
    (50,'HATTON'),
    (51,'NELLIADY'),
    (52,'MATUGAMA'),
    (53,'WENNAPPUWA'),
    (54,'THAMBUTHTHEGAMA'),
    (55,'AKKARAIPATTU'),
    (56,'POTHUVIL'),
    (57,'KOCHCHIKADE'),
    (58,'KOTAHENA'),
    (59,'ANURADHAPURA 02'),
    (60,'RAJAGIRIYA'),
    (61,'WELIMADA'),
    (62,'PILIMATHALAWA'),
    (63,'KATUGASTOTA'),
    (64,'KALMUNAI'),
    (65,'MORATUMULLA'),
    (66,'KALAWANCHIKUDY'),
    (67,'SEA STREET'),
    (68,'MATARA CITY'),
    (69,'ALUTHGAMA'),
    (70,'KANDY CITY'),
    (71,'WARAKAPOLA'),
    (72,'MALABE'),
    (73,'KADUWELA'),
    (74,'NAWALAPITIYA'),
    (75,'HOMAGAMA'),
    (76,'KURUNEGALA CITY'),
    (77,'MASKELIYA'),
    (78,'PITIGALA'),
    (79,'SAMMANTURAI'),
    (80,'SAINTHAMARUTHU'),
    (81,'KOTTE'),
    (82,'BADULLA CITY'),
    (83,'JA ELA'),
    (84,'DELKANDA'),
    (85,'ARAYAMPATHY'),
    (86,'DAM STREET'),
    (87,'AKURESSA'),
    (88,'MONARAGALA'),
    (89,'TANGALLE'),
    (90,'MOUNT LAVINIA'),
    (91,'NELUWA'),
    (92,'BATTARAMULLA'),
    (93,'KURUNEGALA PREMIER CENTRE'),
    (94,'MORATUWA'),
    (95,'MEDAWACHCHIYA'),
    (96,'CHENKALADY'),
    (97,'PUSSELLAWA'),
    (98,'DENIYAYA'),
    (99,'JAFFNA CITY'),
    (100,'JAFFNA PREMIER'),
    (101,'VALACHCHENAI'),
    (102,'WATTALA'),
    (103,'GAMPOLA CITY'),
    (104,'KOTTAWA'),
    (105,'DEHIATTAKANDIYA'),
    (106,'KOKKADICHOLAI'),
    (107,'GELIOYA'),
    (108,'KATUGASTOTA CITY'),
    (109,'KINNIYA'),
    (110,'ANAMADUWA'),
    (111,'PUTHUKKUDIYIRUPPU'),
    (112,'DELGODA'),
    (113,'EHELIYAGODA'),
    (114,'KEKIRAWA'),
    (115,'DIVULAPITIYA'),
    (116,'NARAMMALA'),
    (117,'MEDIRIGIRIYA'),
    (118,'ATCHUVELY'),
    (119,'MANNAR'),
    (120,'CITY OFFICE'),
    (121,'DHARGA TOWN'),
    (122,'WADDUWA'),
    (123,'KARAPITIYA'),
    (124,'MINUWANGODA'),
    (126,'THIRUNELVELY'),
    (127,'KOHUWALA'),
    (128,'PREMIER COLOMBO 07'),
    (129,'MARAWILA'),
    (130,'MALLAVI'),
    (149,'WELLAWATTE CITY'),
    (150,'ATHURUGIRIYA'),
    (151,'VADDUKODDAI'),
    (152,'ADDALAICHENAI'),
    (153,'Katunayake - Awariwatta'),
    (154,'CHANKANEI'),
    (155,'ERAVUR'),
    (173,'VAKARAI'),
    (174,'POINT PEDRO'),
    (175,'MAWANELLA'),
    (176,'CENTRAL CAMP'),
    (177,'GALEWELA'),
    (178,'KANTALE'),
    (179,'KALPITIYA'),
    (180,'KIRAN'),
    (181,'AMBALANTHOTA'),
    (182,'KOPAY'),
    (183,'KODIKAMAM'),
    (184,'SERUNUWARA'),
    (185,'NOCHCHIYAGAMA'),
    (186,'Thirukkovil'),
    (187,'DIGANA'),
    (188,'TELLIPPALAI'),
    (189,'TRINCOMALEE CITY'),
    (190,'PESALAI'),
    (191,'VAVUNATHIVU'),
    (192,'MARUTHANKERNY'),
    (193,'BORELLA CITY'),
    (194,'VALVETTITHURAI'),
    (195,'Pandatharippu'),
    (196,'KAITHADY'),
    (197,'RAGALA'),
    (198,'NANATTAN'),
    (199,'PALLAI'),
    (200,'POONAKARY'),
    (201,'HENDALA'),
    (202,'ANURADHAPURA METRO'),
    (203,'RATNAPURA CITY'),
    (204,'GAMPAHA CITY'),
    (205,'PERADENIYA'),
    (206,'KURUNAGALA METRO'),
    (207,'MATARA METRO'),
    (208,'MARADANA CITY'),
    (209,'URUMPIRAI'),
    (210,'PANADURA PREMIER'),
    (211,'KOTIKAWATTA'),
    (212,'ERAGAMA'),
    (213,'NINTAVUR'),
    (214,'URAGASMANHANDIYA'),
    (215,'WELIGAMA'),
    (216,'WELLAWAYA'),
    (217,'KATANA'),
    (500,'ALUTH MAWATHA'),
    (501,'ATHTHIDIYA'),
    (502,'BANDARAGAMA'),
    (503,'BERUWALA'),
    (504,'BORELLA'),
    (505,'DEANS ROAD'),
    (506,'DEHIWALA CITY'),
    (507,'DEMATAGODA'),
    (508,'ELAKANDA'),
    (509,'RATMALANA'),
    (510,'GRANDPASS'),
    (512,'GRANDPASS SULAIMAN'),
    (514,'JAMPATTAH'),
    (515,'KELANIYA'),
    (516,'KESELWATTA'),
    (518,'KIRIBATHGODA MAKOLA'),
    (519,'KIRULAPANA'),
    (520,'KOLONNAWA'),
    (522,'MAHARAGAMA CITY'),
    (523,'MALIGAWATTA'),
    (524,'MATTAKKULIYA'),
    (525,'MODARA'),
    (526,'NEGOMBO CITY'),
    (527,'NITTAMBUWA'),
    (528,'RAGAMA'),
    (529,'SANGARAJA MAWATHA'),
    (530,'SLAVE ISLAND'),
    (531,'THIHARIYA'),
    (532,'THOTALANGA'),
    (533,'WELLAWATTA'),
    (534,'GANEMULLA'),
    (535,'GOTHATUWA NEW TOWN'),
    (536,'NARAHENPITA'),
    (537,'BADURALIYA'),
    (538,'HANWELLA'),
    (541,'MULLAITIVU')

]

# Convert to dictionary: Branch Name → ID
branch_map = {name: branch_id for branch_id, name in branches}

# Save to JSON
with open("branch_map.json", "w", encoding="utf-8") as f:
    json.dump(branch_map, f, ensure_ascii=False, indent=4)

print("branch_map.json created successfully!")